CHANGELOG for v0.1.x.md
README.md
packages/Webkul/PWA/composer.json
packages/Webkul/PWA/src/Config/menu.php
packages/Webkul/PWA/src/Contracts/PushNotification.php
packages/Webkul/PWA/src/DataGrids/PushNotificationDataGrid.php
packages/Webkul/PWA/src/Http/Controllers/PushNotificationController.php
packages/Webkul/PWA/src/Models/PushNotification.php
packages/Webkul/PWA/src/Providers/ModuleServiceProvider.php
packages/Webkul/PWA/src/Providers/PWAServiceProvider.php
packages/Webkul/PWA/src/Repositories/PushNotificationRepository.php
packages/Webkul/PWA/src/Resources/lang/en/app.php
packages/Webkul/PWA/src/Resources/views/PushNotification/create.blade.php
packages/Webkul/PWA/src/Resources/views/PushNotification/edit.blade.php
packages/Webkul/PWA/src/Resources/views/PushNotification/index.blade.php

[Added models contracts and missing translation.]

[Added models contracts and missing translation.]

---

src/Http/Resources/Catalog/Product.php
src/Resources/assets/js/components/products/gallery-images.vue
src/Resources/assets/sass/app.scss
src/Resources/assets/sass/rtl.scss
src/Resources/views/master.blade.php

rtl updates

---

src/Resources/assets/js/components/products/bundle-option-item.vue
src/Resources/assets/js/components/products/bundle-options.vue
src/Resources/assets/js/components/products/downloadable-options.vue
src/Resources/assets/js/components/products/index.vue
src/Resources/assets/sass/app.scss

bundle product type compatibility

bundle product type compatibility

---

package.json
src/Http/Resources/Catalog/Product.php
src/Resources/assets/js/components/products/booking-options.vue
src/Resources/assets/js/components/products/booking/appointment.vue
src/Resources/assets/js/components/products/booking/date.vue
src/Resources/assets/js/components/products/booking/default-view.vue
src/Resources/assets/js/components/products/booking/event.vue
src/Resources/assets/js/components/products/booking/rental.vue
src/Resources/assets/js/components/products/booking/slots.vue
src/Resources/assets/js/components/products/booking/table.vue
src/Resources/assets/js/components/products/index.vue
src/Resources/assets/js/components/products/price.vue
src/Resources/assets/js/lang/en.json
src/Resources/assets/js/plugins/push-notification.js
src/Resources/assets/sass/app.scss
src/Resources/views/master.blade.php

booking product type compatibility

booking product type compatibility

---

src/Resources/views/master.blade.php

remove ui.js from master blade

remove ui.js from master blade

---

src/Http/Resources/Sales/DownloadableProduct.php
src/Resources/assets/js/components/customers/account/sales/orders/downloadable-products.vue
src/Resources/assets/js/lang/en.json

downloadable products section in customer menu

downloadable products section in customer menu

---

src/Http/Controllers/PushNotificationController.php

comment added and removed unused code

comment added and removed unused code

---

src/Listeners/CoreConfig.php
src/Providers/EventServiceProvider.php
src/Providers/PWAServiceProvider.php
src/Resources/views/master.blade.php

add to home page functionality implemented

add to home page functionality implemented

---

src/Config/system.php
src/Resources/lang/en/app.php
src/Resources/views/master.blade.php

dynamic PWA SEO

---

src/Http/Controllers/Shop/CartController.php

fixed wishlist repository issue

fixed wishlist repository issue

---

CHANGELOG for v1.2.0.md
README.md

CHANGELOG & README updated

---

src/Resources/views/master.blade.php

fixed route issue for SAAS

---

src/Resources/views/master.blade.php

revert changes

---

src/Http/Controllers/Shop/API/APIController.php
src/Resources/views/master.blade.php

fixed errors

---

src/Http/Controllers/Shop/CartController.php

cart API update

---

src/DataGrids/PushNotificationDataGrid.php
src/Http/Controllers/Admin/PushNotificationController.php
src/Http/Controllers/Shop/CartController.php
src/Http/Controllers/Shop/CheckoutController.php
src/Http/Controllers/Shop/InvoiceController.php
src/Http/Controllers/Shop/ProductController.php
src/Http/Controllers/Shop/ReviewController.php
src/Http/Controllers/Shop/WishlistController.php
src/Http/Controllers/SinglePageController.php
src/Providers/EventServiceProvider.php
src/Providers/PWAServiceProvider.php

added webkul as author and resolved issue while push notification

added webkul as author and resolved issue while push notification

---

src/Http/Controllers/Shop/API/APIController.php

fixed issue #198

---

src/Config/system.php
src/Helpers/AdminHelper.php
src/Http/Controllers/SinglePageController.php
src/Resources/lang/en/app.php

[Updated: added module status check.]

[Updated: added module status check.]

---

CHANGELOG for v1.4.x.md
src/Helpers/PwaConfigurableOption.php

Compatibility with Bagisto v1.4.3 and fix a dependency error of $productImage on src/Helpers/PwaConfigurableOption.php

Compatibility with v1.4.3

---

README.md
publishable/assets/css/pwa-admin.css
publishable/assets/css/pwa.css
publishable/assets/js/app.js
publishable/assets/mix-manifest.json
src/Models/PWALayout.php
src/Providers/PWAServiceProvider.php
src/Resources/assets/js/components/products/index.vue
src/Resources/assets/js/components/products/social-links.vue
src/Resources/views/master.blade.php

Resolve installation issue.
